application: gaephotos2
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: django
  version: "1.2"

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /static
  static_dir: static

- url: /.*
  script: main.app

error_handlers:
  - error_code: over_quota
    file: templates/over_quota.html